apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo-api
  namespace: microservices-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: microservices-demo-api
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microservices-demo-api
    spec:
      containers:
      - name: microservices-demo-api
        image: microservices-demo-api
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
          # Postgresql config
          - name: DB_HOST
            value: "public-micro-app-pg-qmpedhpqpizq.db.upclouddatabases.com"
          - name: DB_PORT
            value: "11569"
          - name: DB_NAME
            value: "microdb01"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-demo-api-svc
  namespace: microservices-demo
spec:
  selector:
    app.kubernetes.io/name: microservices-demo-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
