apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vso-microservices-demo-db
  namespace: microservices-demo
spec:

  # Mount path of the secrets backend
  mount: micro-db

  # Path to the secret
  path: creds/dev-postgres

  # Where to store the secrets, end user will create the secret
  destination:
    create: false
    name: postgresql

  # Restart these pods when secrets rotated
  rolloutRestartTargets:
  - kind: Deployment
    name: microservices-demo-api

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: dynamic-auth